#!/usr/bin/env node
const fs = require('fs')
main()

function main() {
  try {
    const pattern = /^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z ]+\))?:[\w ]+$/g
    const message = fs.readFileSync(process.argv[2], 'utf8').trim()
    if (!pattern.test(message)) {
      throw new Error('conventional commit validation failed')
    }
  } catch (err) {
    throw new Error('conventional commit validation failed')
  }
}
