cache:
  key: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}"
  untracked: true
  paths:
    - node_modules/

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DEPLOY_TOKEN: "gitlab+deploy-token-14:Ftfs58bYKnybeW8LY511"

before_script:
  - apk add git
  - git checkout $CI_COMMIT_REF_NAME
  - if [ "$CI_COMMIT_REF_NAME" == "develop" -o "$CI_COMMIT_REF_NAME" == "master" ]; then git pull; fi
  - pwd
  - ls gitlab
  - ./gitlab/before_script.sh

stages:
  - test
  - deploy
  - openapi
  - release

test:
  stage: test
  only:
    - develop
    - master
    - tags
  script:
    ./gitlab/test.sh

deploy:
  stage: deploy
  only:
    - develop
    - master
    - tags
  script:
    ./gitlab/deploy.sh

openapi:
  stage: openapi
  only:
    - develop
    - master
    - tags
  script:
    ./gitlab/openapi.sh

release:
  stage: release
  only:
    - tags
  script:
    ./gitlab/release.sh
