apiVersion: template.openshift.io/v1
kind: Template
labels:
  name: ${APP_NAME}
message: |-
  The following service(s)...
metadata:
  annotations:
    description: |-
      An template that helps CD pipeline process
    iconClass: fa
    openshift.io/display-name: Template Helper for Pipeline
  name: template-helper-for-pipeline
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    generation: 1
    labels:
      name: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        name: ${APP_NAME}
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: ${APP_NAME}
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/${APP_NAME}:${TAG_VERSION}
          imagePullPolicy: Always
          name: ${APP_NAME}
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          envFrom:
            - configMapRef:
                name: genesis-cm
            - secretRef:
                name: genesis-db-secret              
          resources: {}
          # readinessProbe:
          #     httpGet:
          #       path: /api/health/
          #       port: 8080
          #       scheme: HTTP
          #     initialDelaySeconds: 0
          #     timeoutSeconds: 5
          #     periodSeconds: 10
          #     successThreshold: 1
          #     failureThreshold: 3
          # livenessProbe:
          #     httpGet:
          #       path: /api/health/
          #       port: 8080
          #       scheme: HTTP
          #     initialDelaySeconds: 10
          #     timeoutSeconds: 1
          #     periodSeconds: 10
          #     successThreshold: 1
          #     failureThreshold: 3  
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
parameters:
- description: The OpenShift Namespace where the ImageStream resides.
  displayName: Namespace
  name: NAMESPACE
  required: true
- description: The Application Name.
  displayName: AppName
  name: APP_NAME
  required: true
- description: The TAG Name.
  displayName: App TAG Name
  name: TAG_VERSION
  required: true